modules/ROOT/pages/dataweave-cookbook-add-and-subtract-time.adoc
=> DOCS-11922-2.4-updating-xref-cloudHub- kt

modules/ROOT/pages/dataweave-cookbook-csv-lookup.adoc, modules/ROOT/pages/dataweave-cookbook-defaults.adoc
Removing Mule terminology in Set default values example
=> DOCS-11922-2.4-remove-mule-kt

modules/ROOT/pages/_partials/dataweave-intro.adoc, modules/ROOT/pages/index.adoc
=> DOCS-11612-dw-index-2.3-cv

modules/ROOT/pages/_partials/dataweave-intro.adoc, modules/ROOT/pages/index.adoc
=> Docs 11612 dw index 2.4 cv

modules/ROOT/pages/dataweave-troubleshoot.adoc
Added DW warning to sync with Mule 4.3
=> DOCS-11987-eoi-update-v2.3-cv

modules/ROOT/pages/dataweave-troubleshoot.adoc
Added warning to sync with Mule v4.3
=> Docs 11987 eoi update v2.4 cv

modules/ROOT/nav.adoc, modules/ROOT/pages/dataweave-formats.adoc, modules/ROOT/pages/dataweave-indexed-readers.adoc
=> DOCS-11843-2.4-indexed-readers-kt 

modules/ROOT/pages/dw-dataformat-types.adoc, modules/ROOT/pages/dw-functions.adoc
Fix page aliases and title heading
=> DOCS-12237-2.3-DW-page-aliases-fix-kt

modules/ROOT/pages/dw-dataformat-types.adoc
=> DOCS-12237-2.2-DW-page-aliases-fix-kt

modules/ROOT/pages/dataweave-reference-documentation.adoc
DOCS-12259-DWv10xrefs-4-duke fix dup xrefs
=> DOCS-12259-DWv10xrefs-3-duke

modules/ROOT/pages/dataweave-indexed-readers.adoc, modules/ROOT/pages/whats-new-in-dw.adoc
Created anchor, changed xref link
=> DOCS-12018-dw-fix-cv

modules/ROOT/pages/dw-arrays-functions-every.adoc
Verified with Mariano De Achaval and Ana Felisatti before creating PR.
=> DOCS-12481: Update dw-arrays-functions-every.adoc

modules/ROOT/pages/dataweave-formats-multipart.adoc
Added iterate multipart example
=> DOCS-10985-dw-multipart-sample-kt

modules/ROOT/pages/dataweave-variables-context.adoc
Added field, clarified description of errorType
=> DOCS-7436-context-variables-v2.4-cv

modules/ROOT/pages/dataweave-troubleshoot.adoc
Based on SEs about encoding resolved as "Work as Designed". https://www.mulesoft.org/jira/browse/DW-1045
=> DW-1045: Troubleshooting encoding issues

modules/ROOT/pages/dataweave-formats-xml.adoc
It can be tricky to remember where the reader/writer properties are located
=> W-10704738: Added link to the reader/writer properties tables

modules/ROOT/pages/_partials/cookbook-dw/map-an-object-ex02/inputs/payload.json, modules/ROOT/pages/_partials/cookbook-dw/map-an-object-ex02/out.json, modules/ROOT/pages/_partials/cookbook-dw/map-an-object-ex02/transform.dwl, modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
W-10705169 Adding new DW Map Object example
=> W-10705169-dw-object-example-kt

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-10978127-flatFileProp-v44-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-10935528 | Add reader property in FlatFile's config file (v2.3)

modules/ROOT/pages/dataweave-cookbook-change-time-zone.adoc
=> W-11171631-dWtimeZoneFixes-v23-duke

modules/ROOT/pages/dataweave-streaming.adoc
=> W-11156802 and W-11166839: Clarify DW streaming is unrelated to Mule components

modules/ROOT/pages/dataweave-types.adoc
=> W-10589711-dwTypes-v23-duke

CODE_OF_CONDUCT.adoc
=> W-11260863: Update repository link from 'master'  to 'main'.

modules/ROOT/pages/dataweave-formats.adoc, modules/ROOT/pages/dataweave-quickstart.adoc
=> W 11210897 remove pn gs duke

modules/ROOT/pages/dataweave-formats.adoc, modules/ROOT/pages/dataweave-quickstart.adoc
=> W 11210897 more build error fixes duke

modules/ROOT/pages/dataweave-quickstart.adoc, modules/ROOT/pages/dataweave-variables.adoc
=> W 11210897 more build error fixes v21 duke

modules/ROOT/pages/dataweave-examples.adoc, modules/ROOT/pages/dataweave-flat-file-schemas.adoc, modules/ROOT/pages/dataweave-formats.adoc, modules/ROOT/pages/dataweave-language-introduction.adoc, modules/ROOT/pages/dataweave-memory-management.adoc, modules/ROOT/pages/dataweave-migrator.adoc, modules/ROOT/pages/dataweave-operators.adoc, modules/ROOT/pages/dataweave-quickstart.adoc, modules/ROOT/pages/dataweave-reference-documentation.adoc, modules/ROOT/pages/dataweave-selectors.adoc, modules/ROOT/pages/dataweave-troubleshooting.adoc, modules/ROOT/pages/dataweave-types.adoc, modules/ROOT/pages/dataweave-xml-reference.adoc, modules/ROOT/pages/index.adoc
This PR fixes the broken links to older versions of Studio due to the updated 'version' field.
See 
- [W-11585544](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000013ulwzYAA/view) 
- https://github.com/mulesoft/docs-studio/pull/350
- https://github.com/mulesoft/docs-studio/pull/351  
for more details.
=> W-11585544: Update Studio version

modules/ROOT/pages/_partials/cookbook-dw/pluck/inputs/payload.json, modules/ROOT/pages/_partials/cookbook-dw/pluck/out.json, modules/ROOT/pages/_partials/cookbook-dw/pluck/transform.dwl, modules/ROOT/pages/dataweave-cookbook-pluck.adoc
=> W-11610514: dw fix script and convert to includes

modules/ROOT/pages/dataweave-cookbook-remove-objects.adoc
=> W-11610514: Fix JSON refs

modules/ROOT/pages/dataweave-cookbook-select-xml-elements.adoc
=> W-11610514: Fix XML file refs

modules/ROOT/pages/dataweave-cookbook-format-dates.adoc
=> W-11610514: Fix JSON ref

modules/ROOT/pages/dataweave-cookbook-java-methods.adoc, modules/ROOT/pages/dataweave-cookbook-map-based-on-an-external-definition.adoc
=> W-11610514-fixDWscript-duke

modules/ROOT/pages/dataweave-runtime-functions.adoc
=> W-11489041-DWvsMuleProps-duke

modules/ROOT/pages/dataweave-selectors.adoc
=> w-11609405-added a clarification

modules/ROOT/pages/dataweave-examples.adoc
ref: W-11689882
- fix a callout error
- fix some typos
- Dead links
=> [W-11689882] new callouts 1.2

modules/ROOT/pages/dataweave-operators.adoc
ref: W-11689882
- fix a callout error
- fix typo
- Dead links
=> [W-11689882] new callouts 1.1

modules/ROOT/pages/dw-functions.adoc
=> W-11717126-completed list of modules

modules/ROOT/pages/dw-core-functions-mapobject.adoc, modules/ROOT/pages/dw-url-functions-decodeuri.adoc
ref: W-11689882
fix some things to reduce build warnings.
- Dead links
=> [W-11689882] build warnings 2.1

modules/ROOT/pages/dataweave-cookbook-pluck.adoc
=> W-11670348-addXrefs-duke

modules/ROOT/pages/dw-strings-functions-countcharactersby.adoc, modules/ROOT/pages/dw-strings-functions-countmatches.adoc, modules/ROOT/pages/dw-strings-functions-everycharacter.adoc
=> W-11936894-importDirectiveFixes-duke

modules/ROOT/pages/dataweave-type-system.adoc
=> W 12197152 merge1 v24tov25 duke

modules/ROOT/pages/dataweave-functions-lambdas.adoc, modules/ROOT/pages/dataweave-functions.adoc
=> W-12206229: documentation for type parameter application

modules/ROOT/pages/dataweave-troubleshoot.adoc
=> W-11847476. Info of limitation in multipart reader

modules/ROOT/pages/dataweave-selectors.adoc
=> W-12306411-indexSelectorImprovement-v23-duke

modules/ROOT/pages/dataweave-selectors.adoc
=> W-12306411-indexSelectorImprovement-duke

modules/ROOT/pages/dataweave-formats-avro.adoc, modules/ROOT/pages/dataweave-formats-binary.adoc, modules/ROOT/pages/dataweave-formats-csv.adoc, modules/ROOT/pages/dataweave-formats-dw.adoc, modules/ROOT/pages/dataweave-formats-dwb.adoc, modules/ROOT/pages/dataweave-formats-excel.adoc, modules/ROOT/pages/dataweave-formats-flatfile.adoc, modules/ROOT/pages/dataweave-formats-json.adoc, modules/ROOT/pages/dataweave-formats-multipart.adoc, modules/ROOT/pages/dataweave-formats-ndjson.adoc, modules/ROOT/pages/dataweave-formats-properties.adoc, modules/ROOT/pages/dataweave-formats-text.adoc, modules/ROOT/pages/dataweave-formats-urlencoded.adoc, modules/ROOT/pages/dataweave-formats-xml.adoc, modules/ROOT/pages/dataweave-formats-yaml.adoc
=> W 12190419 dwformats docchk v4 duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> w-12190419-dwformats-fixVersionsTweak-duke

modules/ROOT/pages/dataweave-formats-flatfile.adoc
=> w-12190419-dwformats-fixVersionsTweak2-duke

modules/ROOT/pages/dataweave-selectors.adoc, modules/ROOT/pages/dataweave-troubleshoot.adoc
=> W 12417444 merge2 v24intov25 duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12190419-DWv23PropertyFixes-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12190419-DWv24PropertyFixes-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12357357 retain empty string fields on parsing v23 duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12357357 retain empty string fields on parsing v24 duke

modules/ROOT/pages/dataweave-system-properties.adoc
These properties were removed in Feb 2021 before the 2.4 release.
- Dead links
=> W-12364155-dwSystemPropertiesRemoval-duke v2.4

modules/ROOT/pages/dataweave-system-properties.adoc
=> W-12364155 dw system properties v25 duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12468592-lenientDocv25-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12468592-lenientDocv24-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12468592-lenientDocv23-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12401855 merge4 dw v24tov25 duke

modules/ROOT/pages/dataweave-versioning-behavior.adoc
=> W-12508811-removeSelfRefXref-duke

modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc
=> W-12522910-fix-table-ghIssue-duke

antora.yml
=> W-12573768 dw2.2 support Banner-duke

antora.yml
=> W-12573768 dw2.1 support banner duke

modules/ROOT/pages/dw-mule-functions-lookup.adoc
=> W-12607053-add-note-box

modules/ROOT/nav.adoc, modules/ROOT/pages/dataweave-release-notes.adoc, modules/ROOT/pages/whats-new-in-dw.adoc
=> W 12600591 dw whats new retire duke

modules/ROOT/pages/dataweave-formats.adoc
=>  W-12612487-protobuf-in-format-table-duke

modules/ROOT/pages/dataweave-troubleshoot.adoc
=> W-12521512: Add example for allowutf8 property

modules/ROOT/pages/dataweave-cookbook-use-regex.adoc, modules/ROOT/pages/dw-mule-functions-lookup.adoc
=> W-12531802 merge dw24into dw25 merge5 duke

antora.yml
Wait to merge until March 7, 2025.
- Dead links
=> W-12573768 dw 2.3 support banner duke

modules/ROOT/pages/dataweave-cookbook-change-time-zone.adoc
=> W-12609733-remove-reference-tz

antora.yml
=> W-12573768 dw1.2 support banner duke

modules/ROOT/pages/dataweave-cookbook-change-time-zone.adoc
=> W-12653166 merge6 dw24todw25 duke

modules/ROOT/pages/dataweave-types-coercion.adoc
=> W-12748758: Fix date format

modules/ROOT/pages/dataweave-formats-xml.adoc
=> W-12948540-correct-CDATA-dm

modules/ROOT/pages/dataweave-types-coercion.adoc
=> W-13029266 merge7 dw24todw25 duke

antora.yml, modules/ROOT/pages/_partials/eol-warning.adoc
=> W-12573745-eol-v22-duke

modules/ROOT/pages/mytest.adoc
=> Just testing test2

modules/ROOT/pages/dw-mule-functions-p.adoc
=> W-13739807-fix-dw-link

CODEOWNERS
=> W-13736152 Update CODEOWNERS
